apiVersion: v1
kind: Pod
metadata:
  name: pj-web-client
spec:
  restartPolicy: Never
  containers:
  - name: test-client1
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "nslookup pj-web-svc"]
