apiVersion: v1
kind: Pod
metadata:
  name: pj-web-client-nc2
spec:
  restartPolicy: Never
  containers:
  - name: test-client1
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "nc -v -w 2 pj-web-svc 31573"]
