apiVersion: v1
kind: Pod
metadata:
  name: service-client3
spec:
  restartPolicy: Never
  containers:
  - name: service-client
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "echo 'GET / HTTP/1.1\r\n\r\n' | nc service-test 80"]
